spring:
  application:
    name: report-listener
  profiles:
    default: default
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${BROKER_URL}
      function:
        bindings:
          consumerReport-in-0:
            destination: consumerReport
  data:
    mongodb:
      authentication-database: admin
      host: ${MONGO_HOST}
      port: 27017
      username: sa
      password: sa
server:
  port: 0
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.micro.report_listener: INFO
