spring:
  application:
    name: micro-crud-fallback
server:
  servlet:
    context-path: /micro-crud-fallback
  port: 8787
eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

